name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macOS-latest
            target: x86_64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libpango1.0-dev

      - name: Install Dependencies on macOS
        if: matrix.os == 'macOS-latest'
        run: |
          brew install pango gtk+3

      - name: Setup GTK for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install gtk-runtime
          echo "C:\Program Files\GTK3-Runtime Win64\bin" >> $GITHUB_PATH

      - name: Build the binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload the binary to release
        uses: actions/upload-artifact@v3
        with:
          name: keyboard-latency-test-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/keyboard-latency-test*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v3
        with:
          path: release-artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: release-artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: release-artifacts/**